# Generated by Django 3.0.6 on 2020-05-15 15:03

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name=app.models.ItemPrice)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemPrices',
            new_name='ItemPrice',
        ),
        migrations.RenameModel(
            old_name='Baskets',
            new_name='Basket',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='BasketItems',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(to='app.BasketItem'),
        ),
    ]
