# Generated by Django 3.0.6 on 2020-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20200515_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='platform',
            field=models.CharField(
                choices=[('', ''), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PSV', 'PlayStation Vita'),
                         ('PSP', 'PlayStation Portable'), ('PS2', 'PlayStation 2')], default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=999999),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='historical_price',
            field=models.FloatField(default=999999),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.FloatField(default=999999),
        ),
    ]
