# Generated by Django 3.0.6 on 2020-05-15 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_auto_20200515_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='platform',
        ),
    ]
