# Generated by Django 3.0.6 on 2020-05-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_remove_item_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='platform',
            field=models.CharField(
                choices=[('', ''), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PSV', 'PlayStation Vita'),
                         ('PSP', 'PlayStation Portable'), ('PS2', 'PlayStation 2')], default=' ', max_length=3),
        ),
    ]
