# Generated by Django 3.0.6 on 2020-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_item_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='date_fetched',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
