# Generated by Django 3.0.6 on 2020-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_auto_20200515_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='crying.jpg', upload_to=''),
        ),
    ]
