# Generated by Django 3.0.6 on 2020-05-15 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
    ]
